# fly.toml app configuration file generated for uiventures-be on 2023-11-15T13:14:25+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "uiventures-be"
primary_region = "ams"

#[build]
  #image = "waynejr/shopwell-back"

[env]
  JWT_SECRET = "somethingsecret"
  MONGODB_URL = "mongodb+srv://bishop:bishop@restfulcluster.creso.mongodb.net/shopwell?retryWrites=true&w=majority"
  PAYPAL_CLIENT_ID = "db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
