# fly.toml app configuration file generated for uiventures-be on 2023-11-17T12:41:20+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "uiventures-be"
primary_region = "ams"

[build]
   builder = "heroku/buildpacks:20"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
